baseURL = "https://drusellers.com"
languageCode = "en-us"
title = "A Curious Mind"

[params]
startYear = 2001
enableSummary = true
useDescriptionReplaceSummary = true
description = "Curiosity is Life"

[outputs]
home = ["HTML", "RSS", "Bonsai"]

[outputFormats.Bonsai]
baseName = "bonsai"
isPlainText = true
mediaType = "application/ndjson"
notAlternative = true

[params.bonsai]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"]

[markup.goldmark.renderer]
unsafe = true

[mediaTypes]
  [mediaTypes."application/ndjson"]
    suffixes = ['ndjson']