baseURL = "https://drusellers.com/"
languageCode = "en-us"
title = "A Curious Mind"

[params]
startYear = 2001
enableSummary = true
font = "helvetica"
useDescriptionReplaceSummary = true

[outputs]
home = ["HTML", "RSS", "Bonsai"]

[outputFormats.Bonsai]
baseName = "bonsai"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.bonsai]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"]
