[build]
  command = "NITRO_PRESET=netlify npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  port = 3000

# every html page needs this
[[headers]]
  for = "/*.html"
  [headers.values]
  Link = [
    "</images/logo.svg>; rel=preload; as=image"
  ]

[[headers]]
  for = "/assets/*"
  [headers.values]
  Cache-Control = "max-age=31536000, immutable"

[[headers]]
  for = "/images/*.svg"
  [headers.values]
  Cache-Control = "max-age=31536000"

[[headers]]
  for = "/images/*.png"
  [headers.values]
  Cache-Control = "max-age=31536000"

[[headers]]
  for = "/css/*.css"
  [headers.values]
  Cache-Control = "max-age=31536000"

[[redirects]]
  from = "/austin"
  to = "/atx"
  status = 301

[[redirects]]
  from = "/greenpipes/2016/10/30/greenpipes.html"
  to = "/posts/greenpipes"
  status = 301
