/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as DesignSystemRouteImport } from './app/_design-system'
import { Route as OxfordRouteImport } from './app/_oxford'
import { Route as AustinRouteImport } from './app/austin'
import { Route as UnfurlRouteImport } from './app/unfurl'
import { Route as OxfordIndexRouteImport } from './app/_oxford/index'
import { Route as OxfordAboutRouteImport } from './app/_oxford/about'
import { Route as OxfordAllegoryRouteImport } from './app/_oxford/allegory'
import { Route as OxfordAtxRouteImport } from './app/_oxford/atx'
import { Route as OxfordCodeRouteImport } from './app/_oxford/code'
import { Route as OxfordIronRouteImport } from './app/_oxford/iron'
import { Route as OxfordMediaRouteImport } from './app/_oxford/media'
import { Route as OxfordReadmeRouteImport } from './app/_oxford/readme'
import { Route as OxfordResumeRouteImport } from './app/_oxford/resume'
import { Route as OxfordStackRouteImport } from './app/_oxford/stack'
import { Route as OxfordStyleRouteImport } from './app/_oxford/style'
import { Route as TextIdRouteImport } from './app/text/$id'
import { Route as DesignSystemDesignSystemIndexRouteImport } from './app/_design-system/design-system/index'
import { Route as DesignSystemDesignSystemColorsRouteImport } from './app/_design-system/design-system/colors'
import { Route as DesignSystemDesignSystemComponentsRouteImport } from './app/_design-system/design-system/components'
import { Route as DesignSystemDesignSystemFontsRouteImport } from './app/_design-system/design-system/fonts'
import { Route as DesignSystemDesignSystemTypographyRouteImport } from './app/_design-system/design-system/typography'
import { Route as OxfordPostsIndexRouteImport } from './app/_oxford/posts/index'
import { Route as OxfordPostsIdRouteImport } from './app/_oxford/posts/$id'
import { Route as OxfordQuotesIndexRouteImport } from './app/_oxford/quotes/index'
import { Route as OxfordQuotesIdRouteImport } from './app/_oxford/quotes/$id'
import { Route as OxfordTagsIndexRouteImport } from './app/_oxford/tags/index'
import { Route as OxfordTagsIdRouteImport } from './app/_oxford/tags/$id'
import { Route as OxfordValuesIndexRouteImport } from './app/_oxford/values/index'
import { Route as OxfordValuesIdRouteImport } from './app/_oxford/values/$id'

const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/_design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const OxfordRoute = OxfordRouteImport.update({
  id: '/_oxford',
  getParentRoute: () => rootRouteImport,
} as any)
const AustinRoute = AustinRouteImport.update({
  id: '/austin',
  path: '/austin',
  getParentRoute: () => rootRouteImport,
} as any)
const UnfurlRoute = UnfurlRouteImport.update({
  id: '/unfurl',
  path: '/unfurl',
  getParentRoute: () => rootRouteImport,
} as any)
const OxfordIndexRoute = OxfordIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OxfordRoute,
} as any)
const OxfordAboutRoute = OxfordAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => OxfordRoute,
} as any)
const OxfordAllegoryRoute = OxfordAllegoryRouteImport.update({
  id: '/allegory',
  path: '/allegory',
  getParentRoute: () => OxfordRoute,
} as any)
const OxfordAtxRoute = OxfordAtxRouteImport.update({
  id: '/atx',
  path: '/atx',
  getParentRoute: () => OxfordRoute,
} as any)
const OxfordCodeRoute = OxfordCodeRouteImport.update({
  id: '/code',
  path: '/code',
  getParentRoute: () => OxfordRoute,
} as any)
const OxfordIronRoute = OxfordIronRouteImport.update({
  id: '/iron',
  path: '/iron',
  getParentRoute: () => OxfordRoute,
} as any)
const OxfordMediaRoute = OxfordMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => OxfordRoute,
} as any)
const OxfordReadmeRoute = OxfordReadmeRouteImport.update({
  id: '/readme',
  path: '/readme',
  getParentRoute: () => OxfordRoute,
} as any)
const OxfordResumeRoute = OxfordResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => OxfordRoute,
} as any)
const OxfordStackRoute = OxfordStackRouteImport.update({
  id: '/stack',
  path: '/stack',
  getParentRoute: () => OxfordRoute,
} as any)
const OxfordStyleRoute = OxfordStyleRouteImport.update({
  id: '/style',
  path: '/style',
  getParentRoute: () => OxfordRoute,
} as any)
const TextIdRoute = TextIdRouteImport.update({
  id: '/text/$id',
  path: '/text/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemDesignSystemIndexRoute =
  DesignSystemDesignSystemIndexRouteImport.update({
    id: '/design-system/',
    path: '/design-system/',
    getParentRoute: () => DesignSystemRoute,
  } as any)
const DesignSystemDesignSystemColorsRoute =
  DesignSystemDesignSystemColorsRouteImport.update({
    id: '/design-system/colors',
    path: '/design-system/colors',
    getParentRoute: () => DesignSystemRoute,
  } as any)
const DesignSystemDesignSystemComponentsRoute =
  DesignSystemDesignSystemComponentsRouteImport.update({
    id: '/design-system/components',
    path: '/design-system/components',
    getParentRoute: () => DesignSystemRoute,
  } as any)
const DesignSystemDesignSystemFontsRoute =
  DesignSystemDesignSystemFontsRouteImport.update({
    id: '/design-system/fonts',
    path: '/design-system/fonts',
    getParentRoute: () => DesignSystemRoute,
  } as any)
const DesignSystemDesignSystemTypographyRoute =
  DesignSystemDesignSystemTypographyRouteImport.update({
    id: '/design-system/typography',
    path: '/design-system/typography',
    getParentRoute: () => DesignSystemRoute,
  } as any)
const OxfordPostsIndexRoute = OxfordPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => OxfordRoute,
} as any)
const OxfordPostsIdRoute = OxfordPostsIdRouteImport.update({
  id: '/posts/$id',
  path: '/posts/$id',
  getParentRoute: () => OxfordRoute,
} as any)
const OxfordQuotesIndexRoute = OxfordQuotesIndexRouteImport.update({
  id: '/quotes/',
  path: '/quotes/',
  getParentRoute: () => OxfordRoute,
} as any)
const OxfordQuotesIdRoute = OxfordQuotesIdRouteImport.update({
  id: '/quotes/$id',
  path: '/quotes/$id',
  getParentRoute: () => OxfordRoute,
} as any)
const OxfordTagsIndexRoute = OxfordTagsIndexRouteImport.update({
  id: '/tags/',
  path: '/tags/',
  getParentRoute: () => OxfordRoute,
} as any)
const OxfordTagsIdRoute = OxfordTagsIdRouteImport.update({
  id: '/tags/$id',
  path: '/tags/$id',
  getParentRoute: () => OxfordRoute,
} as any)
const OxfordValuesIndexRoute = OxfordValuesIndexRouteImport.update({
  id: '/values/',
  path: '/values/',
  getParentRoute: () => OxfordRoute,
} as any)
const OxfordValuesIdRoute = OxfordValuesIdRouteImport.update({
  id: '/values/$id',
  path: '/values/$id',
  getParentRoute: () => OxfordRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof OxfordIndexRoute
  '/austin': typeof AustinRoute
  '/unfurl': typeof UnfurlRoute
  '/about': typeof OxfordAboutRoute
  '/allegory': typeof OxfordAllegoryRoute
  '/atx': typeof OxfordAtxRoute
  '/code': typeof OxfordCodeRoute
  '/iron': typeof OxfordIronRoute
  '/media': typeof OxfordMediaRoute
  '/readme': typeof OxfordReadmeRoute
  '/resume': typeof OxfordResumeRoute
  '/stack': typeof OxfordStackRoute
  '/style': typeof OxfordStyleRoute
  '/text/$id': typeof TextIdRoute
  '/design-system/colors': typeof DesignSystemDesignSystemColorsRoute
  '/design-system/components': typeof DesignSystemDesignSystemComponentsRoute
  '/design-system/fonts': typeof DesignSystemDesignSystemFontsRoute
  '/design-system/typography': typeof DesignSystemDesignSystemTypographyRoute
  '/posts/$id': typeof OxfordPostsIdRoute
  '/quotes/$id': typeof OxfordQuotesIdRoute
  '/tags/$id': typeof OxfordTagsIdRoute
  '/values/$id': typeof OxfordValuesIdRoute
  '/design-system/': typeof DesignSystemDesignSystemIndexRoute
  '/posts/': typeof OxfordPostsIndexRoute
  '/quotes/': typeof OxfordQuotesIndexRoute
  '/tags/': typeof OxfordTagsIndexRoute
  '/values/': typeof OxfordValuesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof OxfordIndexRoute
  '/austin': typeof AustinRoute
  '/unfurl': typeof UnfurlRoute
  '/about': typeof OxfordAboutRoute
  '/allegory': typeof OxfordAllegoryRoute
  '/atx': typeof OxfordAtxRoute
  '/code': typeof OxfordCodeRoute
  '/iron': typeof OxfordIronRoute
  '/media': typeof OxfordMediaRoute
  '/readme': typeof OxfordReadmeRoute
  '/resume': typeof OxfordResumeRoute
  '/stack': typeof OxfordStackRoute
  '/style': typeof OxfordStyleRoute
  '/text/$id': typeof TextIdRoute
  '/design-system/colors': typeof DesignSystemDesignSystemColorsRoute
  '/design-system/components': typeof DesignSystemDesignSystemComponentsRoute
  '/design-system/fonts': typeof DesignSystemDesignSystemFontsRoute
  '/design-system/typography': typeof DesignSystemDesignSystemTypographyRoute
  '/posts/$id': typeof OxfordPostsIdRoute
  '/quotes/$id': typeof OxfordQuotesIdRoute
  '/tags/$id': typeof OxfordTagsIdRoute
  '/values/$id': typeof OxfordValuesIdRoute
  '/design-system': typeof DesignSystemDesignSystemIndexRoute
  '/posts': typeof OxfordPostsIndexRoute
  '/quotes': typeof OxfordQuotesIndexRoute
  '/tags': typeof OxfordTagsIndexRoute
  '/values': typeof OxfordValuesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_design-system': typeof DesignSystemRouteWithChildren
  '/_oxford': typeof OxfordRouteWithChildren
  '/austin': typeof AustinRoute
  '/unfurl': typeof UnfurlRoute
  '/_oxford/about': typeof OxfordAboutRoute
  '/_oxford/allegory': typeof OxfordAllegoryRoute
  '/_oxford/atx': typeof OxfordAtxRoute
  '/_oxford/code': typeof OxfordCodeRoute
  '/_oxford/iron': typeof OxfordIronRoute
  '/_oxford/media': typeof OxfordMediaRoute
  '/_oxford/readme': typeof OxfordReadmeRoute
  '/_oxford/resume': typeof OxfordResumeRoute
  '/_oxford/stack': typeof OxfordStackRoute
  '/_oxford/style': typeof OxfordStyleRoute
  '/text/$id': typeof TextIdRoute
  '/_oxford/': typeof OxfordIndexRoute
  '/_design-system/design-system/colors': typeof DesignSystemDesignSystemColorsRoute
  '/_design-system/design-system/components': typeof DesignSystemDesignSystemComponentsRoute
  '/_design-system/design-system/fonts': typeof DesignSystemDesignSystemFontsRoute
  '/_design-system/design-system/typography': typeof DesignSystemDesignSystemTypographyRoute
  '/_oxford/posts/$id': typeof OxfordPostsIdRoute
  '/_oxford/quotes/$id': typeof OxfordQuotesIdRoute
  '/_oxford/tags/$id': typeof OxfordTagsIdRoute
  '/_oxford/values/$id': typeof OxfordValuesIdRoute
  '/_design-system/design-system/': typeof DesignSystemDesignSystemIndexRoute
  '/_oxford/posts/': typeof OxfordPostsIndexRoute
  '/_oxford/quotes/': typeof OxfordQuotesIndexRoute
  '/_oxford/tags/': typeof OxfordTagsIndexRoute
  '/_oxford/values/': typeof OxfordValuesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/austin'
    | '/unfurl'
    | '/about'
    | '/allegory'
    | '/atx'
    | '/code'
    | '/iron'
    | '/media'
    | '/readme'
    | '/resume'
    | '/stack'
    | '/style'
    | '/text/$id'
    | '/design-system/colors'
    | '/design-system/components'
    | '/design-system/fonts'
    | '/design-system/typography'
    | '/posts/$id'
    | '/quotes/$id'
    | '/tags/$id'
    | '/values/$id'
    | '/design-system/'
    | '/posts/'
    | '/quotes/'
    | '/tags/'
    | '/values/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/austin'
    | '/unfurl'
    | '/about'
    | '/allegory'
    | '/atx'
    | '/code'
    | '/iron'
    | '/media'
    | '/readme'
    | '/resume'
    | '/stack'
    | '/style'
    | '/text/$id'
    | '/design-system/colors'
    | '/design-system/components'
    | '/design-system/fonts'
    | '/design-system/typography'
    | '/posts/$id'
    | '/quotes/$id'
    | '/tags/$id'
    | '/values/$id'
    | '/design-system'
    | '/posts'
    | '/quotes'
    | '/tags'
    | '/values'
  id:
    | '__root__'
    | '/_design-system'
    | '/_oxford'
    | '/austin'
    | '/unfurl'
    | '/_oxford/about'
    | '/_oxford/allegory'
    | '/_oxford/atx'
    | '/_oxford/code'
    | '/_oxford/iron'
    | '/_oxford/media'
    | '/_oxford/readme'
    | '/_oxford/resume'
    | '/_oxford/stack'
    | '/_oxford/style'
    | '/text/$id'
    | '/_oxford/'
    | '/_design-system/design-system/colors'
    | '/_design-system/design-system/components'
    | '/_design-system/design-system/fonts'
    | '/_design-system/design-system/typography'
    | '/_oxford/posts/$id'
    | '/_oxford/quotes/$id'
    | '/_oxford/tags/$id'
    | '/_oxford/values/$id'
    | '/_design-system/design-system/'
    | '/_oxford/posts/'
    | '/_oxford/quotes/'
    | '/_oxford/tags/'
    | '/_oxford/values/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DesignSystemRoute: typeof DesignSystemRouteWithChildren
  OxfordRoute: typeof OxfordRouteWithChildren
  AustinRoute: typeof AustinRoute
  UnfurlRoute: typeof UnfurlRoute
  TextIdRoute: typeof TextIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_design-system': {
      id: '/_design-system'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_oxford': {
      id: '/_oxford'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof OxfordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/austin': {
      id: '/austin'
      path: '/austin'
      fullPath: '/austin'
      preLoaderRoute: typeof AustinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unfurl': {
      id: '/unfurl'
      path: '/unfurl'
      fullPath: '/unfurl'
      preLoaderRoute: typeof UnfurlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_oxford/': {
      id: '/_oxford/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof OxfordIndexRouteImport
      parentRoute: typeof OxfordRoute
    }
    '/_oxford/about': {
      id: '/_oxford/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof OxfordAboutRouteImport
      parentRoute: typeof OxfordRoute
    }
    '/_oxford/allegory': {
      id: '/_oxford/allegory'
      path: '/allegory'
      fullPath: '/allegory'
      preLoaderRoute: typeof OxfordAllegoryRouteImport
      parentRoute: typeof OxfordRoute
    }
    '/_oxford/atx': {
      id: '/_oxford/atx'
      path: '/atx'
      fullPath: '/atx'
      preLoaderRoute: typeof OxfordAtxRouteImport
      parentRoute: typeof OxfordRoute
    }
    '/_oxford/code': {
      id: '/_oxford/code'
      path: '/code'
      fullPath: '/code'
      preLoaderRoute: typeof OxfordCodeRouteImport
      parentRoute: typeof OxfordRoute
    }
    '/_oxford/iron': {
      id: '/_oxford/iron'
      path: '/iron'
      fullPath: '/iron'
      preLoaderRoute: typeof OxfordIronRouteImport
      parentRoute: typeof OxfordRoute
    }
    '/_oxford/media': {
      id: '/_oxford/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof OxfordMediaRouteImport
      parentRoute: typeof OxfordRoute
    }
    '/_oxford/readme': {
      id: '/_oxford/readme'
      path: '/readme'
      fullPath: '/readme'
      preLoaderRoute: typeof OxfordReadmeRouteImport
      parentRoute: typeof OxfordRoute
    }
    '/_oxford/resume': {
      id: '/_oxford/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof OxfordResumeRouteImport
      parentRoute: typeof OxfordRoute
    }
    '/_oxford/stack': {
      id: '/_oxford/stack'
      path: '/stack'
      fullPath: '/stack'
      preLoaderRoute: typeof OxfordStackRouteImport
      parentRoute: typeof OxfordRoute
    }
    '/_oxford/style': {
      id: '/_oxford/style'
      path: '/style'
      fullPath: '/style'
      preLoaderRoute: typeof OxfordStyleRouteImport
      parentRoute: typeof OxfordRoute
    }
    '/text/$id': {
      id: '/text/$id'
      path: '/text/$id'
      fullPath: '/text/$id'
      preLoaderRoute: typeof TextIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_design-system/design-system/': {
      id: '/_design-system/design-system/'
      path: '/design-system'
      fullPath: '/design-system/'
      preLoaderRoute: typeof DesignSystemDesignSystemIndexRouteImport
      parentRoute: typeof DesignSystemRoute
    }
    '/_design-system/design-system/colors': {
      id: '/_design-system/design-system/colors'
      path: '/design-system/colors'
      fullPath: '/design-system/colors'
      preLoaderRoute: typeof DesignSystemDesignSystemColorsRouteImport
      parentRoute: typeof DesignSystemRoute
    }
    '/_design-system/design-system/components': {
      id: '/_design-system/design-system/components'
      path: '/design-system/components'
      fullPath: '/design-system/components'
      preLoaderRoute: typeof DesignSystemDesignSystemComponentsRouteImport
      parentRoute: typeof DesignSystemRoute
    }
    '/_design-system/design-system/fonts': {
      id: '/_design-system/design-system/fonts'
      path: '/design-system/fonts'
      fullPath: '/design-system/fonts'
      preLoaderRoute: typeof DesignSystemDesignSystemFontsRouteImport
      parentRoute: typeof DesignSystemRoute
    }
    '/_design-system/design-system/typography': {
      id: '/_design-system/design-system/typography'
      path: '/design-system/typography'
      fullPath: '/design-system/typography'
      preLoaderRoute: typeof DesignSystemDesignSystemTypographyRouteImport
      parentRoute: typeof DesignSystemRoute
    }
    '/_oxford/posts/': {
      id: '/_oxford/posts/'
      path: '/posts'
      fullPath: '/posts/'
      preLoaderRoute: typeof OxfordPostsIndexRouteImport
      parentRoute: typeof OxfordRoute
    }
    '/_oxford/posts/$id': {
      id: '/_oxford/posts/$id'
      path: '/posts/$id'
      fullPath: '/posts/$id'
      preLoaderRoute: typeof OxfordPostsIdRouteImport
      parentRoute: typeof OxfordRoute
    }
    '/_oxford/quotes/': {
      id: '/_oxford/quotes/'
      path: '/quotes'
      fullPath: '/quotes/'
      preLoaderRoute: typeof OxfordQuotesIndexRouteImport
      parentRoute: typeof OxfordRoute
    }
    '/_oxford/quotes/$id': {
      id: '/_oxford/quotes/$id'
      path: '/quotes/$id'
      fullPath: '/quotes/$id'
      preLoaderRoute: typeof OxfordQuotesIdRouteImport
      parentRoute: typeof OxfordRoute
    }
    '/_oxford/tags/': {
      id: '/_oxford/tags/'
      path: '/tags'
      fullPath: '/tags/'
      preLoaderRoute: typeof OxfordTagsIndexRouteImport
      parentRoute: typeof OxfordRoute
    }
    '/_oxford/tags/$id': {
      id: '/_oxford/tags/$id'
      path: '/tags/$id'
      fullPath: '/tags/$id'
      preLoaderRoute: typeof OxfordTagsIdRouteImport
      parentRoute: typeof OxfordRoute
    }
    '/_oxford/values/': {
      id: '/_oxford/values/'
      path: '/values'
      fullPath: '/values/'
      preLoaderRoute: typeof OxfordValuesIndexRouteImport
      parentRoute: typeof OxfordRoute
    }
    '/_oxford/values/$id': {
      id: '/_oxford/values/$id'
      path: '/values/$id'
      fullPath: '/values/$id'
      preLoaderRoute: typeof OxfordValuesIdRouteImport
      parentRoute: typeof OxfordRoute
    }
  }
}

interface DesignSystemRouteChildren {
  DesignSystemDesignSystemColorsRoute: typeof DesignSystemDesignSystemColorsRoute
  DesignSystemDesignSystemComponentsRoute: typeof DesignSystemDesignSystemComponentsRoute
  DesignSystemDesignSystemFontsRoute: typeof DesignSystemDesignSystemFontsRoute
  DesignSystemDesignSystemTypographyRoute: typeof DesignSystemDesignSystemTypographyRoute
  DesignSystemDesignSystemIndexRoute: typeof DesignSystemDesignSystemIndexRoute
}

const DesignSystemRouteChildren: DesignSystemRouteChildren = {
  DesignSystemDesignSystemColorsRoute: DesignSystemDesignSystemColorsRoute,
  DesignSystemDesignSystemComponentsRoute:
    DesignSystemDesignSystemComponentsRoute,
  DesignSystemDesignSystemFontsRoute: DesignSystemDesignSystemFontsRoute,
  DesignSystemDesignSystemTypographyRoute:
    DesignSystemDesignSystemTypographyRoute,
  DesignSystemDesignSystemIndexRoute: DesignSystemDesignSystemIndexRoute,
}

const DesignSystemRouteWithChildren = DesignSystemRoute._addFileChildren(
  DesignSystemRouteChildren,
)

interface OxfordRouteChildren {
  OxfordAboutRoute: typeof OxfordAboutRoute
  OxfordAllegoryRoute: typeof OxfordAllegoryRoute
  OxfordAtxRoute: typeof OxfordAtxRoute
  OxfordCodeRoute: typeof OxfordCodeRoute
  OxfordIronRoute: typeof OxfordIronRoute
  OxfordMediaRoute: typeof OxfordMediaRoute
  OxfordReadmeRoute: typeof OxfordReadmeRoute
  OxfordResumeRoute: typeof OxfordResumeRoute
  OxfordStackRoute: typeof OxfordStackRoute
  OxfordStyleRoute: typeof OxfordStyleRoute
  OxfordIndexRoute: typeof OxfordIndexRoute
  OxfordPostsIdRoute: typeof OxfordPostsIdRoute
  OxfordQuotesIdRoute: typeof OxfordQuotesIdRoute
  OxfordTagsIdRoute: typeof OxfordTagsIdRoute
  OxfordValuesIdRoute: typeof OxfordValuesIdRoute
  OxfordPostsIndexRoute: typeof OxfordPostsIndexRoute
  OxfordQuotesIndexRoute: typeof OxfordQuotesIndexRoute
  OxfordTagsIndexRoute: typeof OxfordTagsIndexRoute
  OxfordValuesIndexRoute: typeof OxfordValuesIndexRoute
}

const OxfordRouteChildren: OxfordRouteChildren = {
  OxfordAboutRoute: OxfordAboutRoute,
  OxfordAllegoryRoute: OxfordAllegoryRoute,
  OxfordAtxRoute: OxfordAtxRoute,
  OxfordCodeRoute: OxfordCodeRoute,
  OxfordIronRoute: OxfordIronRoute,
  OxfordMediaRoute: OxfordMediaRoute,
  OxfordReadmeRoute: OxfordReadmeRoute,
  OxfordResumeRoute: OxfordResumeRoute,
  OxfordStackRoute: OxfordStackRoute,
  OxfordStyleRoute: OxfordStyleRoute,
  OxfordIndexRoute: OxfordIndexRoute,
  OxfordPostsIdRoute: OxfordPostsIdRoute,
  OxfordQuotesIdRoute: OxfordQuotesIdRoute,
  OxfordTagsIdRoute: OxfordTagsIdRoute,
  OxfordValuesIdRoute: OxfordValuesIdRoute,
  OxfordPostsIndexRoute: OxfordPostsIndexRoute,
  OxfordQuotesIndexRoute: OxfordQuotesIndexRoute,
  OxfordTagsIndexRoute: OxfordTagsIndexRoute,
  OxfordValuesIndexRoute: OxfordValuesIndexRoute,
}

const OxfordRouteWithChildren =
  OxfordRoute._addFileChildren(OxfordRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  DesignSystemRoute: DesignSystemRouteWithChildren,
  OxfordRoute: OxfordRouteWithChildren,
  AustinRoute: AustinRoute,
  UnfurlRoute: UnfurlRoute,
  TextIdRoute: TextIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
